### ISSUE TITLE
Ubuntu 16.04 server.js fails to run

### ISSUE THREAD

**Issue by ghost** [brannondorsey/distributed-password-cracking#1]
Here is the error
:~/distributed-password-cracking$ node server.js
/home/nuc/distributed-password-cracking/src/PasswordDelegator.js:5
class PasswordDelegator {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/nuc/distributed-password-cracking/server.js:6:27)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
nuc@ubuntuserver:~/distributed-password-cracking$

**Comment by brannondorsey** [comment]
That looks to me like you are running the project with an old version of Node. Try upgrading Node, or using [NVM](https://github.com/creationix/nvm) to do so.

**Comment by BackToPyramidOne** [comment]
Yep, works now. Strange as I updated mode using the tar file on their website. Thanks for the quick response
